### ISSUE TITLE
Works incorrectly

### ISSUE THREAD

**Issue by zdm** [leejo/css-packer-perl#7]
Hi,
Please, run it several times with compress => 'pretty' for the following CSS:
```
.x-ie8 .x-mask{
    background-image:url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7)}
```
you will get:
```
.x-ie8 .x-mask{
    background-image:url(data:image/gif;




base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7)}
```

and it will add new line on each run.

**Comment by leejo** [comment]
I'll add a test case and fix shorty (i.e. sometime this week). Ta!

**Comment by leejo** [comment]
v2.06 on its way to CPAN. Thanks!
