### ISSUE TITLE
pretty mode improvements

### ISSUE THREAD

**Issue by zdm** [leejo/css-packer-perl#8]
Hi,
I am using the following hack to produce CSS with indents:
```
use CSS::Packer qw[];

my $PACKER = do {
    my $packer = CSS::Packer->init;

    $packer->{old_declaration_replacement} = $packer->{declaration}->{reggrp_data}->[0]->{replacement};

    $packer->{declaration}->{reggrp_data}->[0]->{replacement} = sub {
        return q[ ] x 4 . $packer->{old_declaration_replacement}->(@_);
    };

    $packer->{_reggrp_declaration} = Regexp::RegGrp->new( { reggrp => $packer->{declaration}->{reggrp_data} } );

    $packer;
};

$PACKER->minify( \$css, { compress => 'pretty' } );
```

Maybe you can implement this mode in your code?
API can be, for example:
```
$PACKER->minify( \$css, { compress => 'pretty' , indent => 4} );
```
If indent is 0 - do not use indentation, if > 0 - use defined spaces number for indentation.

**Comment by leejo** [comment]
Looks useful, think you could create a PR for this?

**Comment by zdm** [comment]
Yes, will do.

**Comment by leejo** [comment]
Resolved by #9

**Comment by zdm** [comment]
Something wrong with the CPAN dist.
File t/stylesheets/s2-expected-indent.css is missed.

**Comment by leejo** [comment]
I missed a file in the MANIFEST, v2.07 on its way to CPAN to fix this.
